# Generated by Django 4.2.13 on 2024-05-17 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="poll",
            table=None,
        ),
    ]
