# Generated by Django 4.2.13 on 2024-05-18 14:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0002_alter_poll_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="agreeRate",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="disagreeRate",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=5
            ),
        ),
    ]
